### ISSUE TITLE
Single Responsibility Principle - wrong example

### ISSUE THREAD

**Issue by dzentota** [jupeter/clean-code-php#13]
You can NOT call `$this->auth->verifyCredentials()` because `verifyCredentials()` is protected

**Comment by TomasVotruba** [comment]
How would you solve that?

**Comment by dzentota** [comment]
make verifyCredentials public

**Comment by TomasVotruba** [comment]
Could you send PR with that?

**Comment by peter-gribanov** [comment]
Fix in PR #28

**Comment by TomasVotruba** [comment]
@peter-gribanov Ah, thanks for the reference.

Closed by #28
