### ISSUE TITLE
Change from JS to PHP in "Functions should only be one level of abstraction"

### ISSUE THREAD

**Issue by oribro** [jupeter/clean-code-php#158]
Function and class names should be updated for PHP, shouldn't they? This is otherwise confusing

**Comment by przemo-hemmersbach** [comment]
I think "`BetterJSAlternative`" is a proper name of actual programming language, just like Typescript, Coffescript, etc.

This function actually parse code written in that language.

However, I agree that that's a readability issue. I'm not native English, and parsing this name was a distraction.

I propose to change it to:
`parseOrderBidFormat`

This way it's something concreet and understandable even with basic command of English.
