### ISSUE TITLE
Need help to understand the Avoid Conditionals section.

### ISSUE THREAD

**Issue by piercemcgeough** [jupeter/clean-code-php#172]
Love this repo! I have one issue that I just can't get my head around. https://github.com/jupeter/clean-code-php#avoid-conditionals

I get that its better to do the following `(new AirForceOne())->getCruisingAltitude();`.
However I still dont see the check to use AirForceOne over the 777.

Are you not just pushing that logic up higher then to a controller.
```
switch ($this->inputValue) {
    case '777':
        return (new Boeing777())->getCruisingAltitude();
    case 'Air Force One':
        return (new AirForceOne())->getCruisingAltitude();
    case 'Cessna':
        return (new Cessna())->getCruisingAltitude();
}
```

**Comment by peter-gribanov** [comment]
The above example is a [Strategy pattern](https://en.wikipedia.org/wiki/Strategy_pattern). We encapsulate the logic of obtaining cruising altitude in specific airplane implementations. The [Factory pattern](https://en.wikipedia.org/wiki/Factory_method_pattern) is best suited to create an instance of a specific airplane. This is necessary to hide the internal business logic from the clients:

```php
$airplane = AirplaneFactory::create($this->inputValue);
$altitude = $airplane->getCruisingAltitude();
```

**Comment by piercemcgeough** [comment]
That makes so much sense seeing wrote out. Thanks
