### ISSUE TITLE
Variable name mismatch

### ISSUE THREAD

**Issue by thedebian** [jupeter/clean-code-php#27]
Hi,
There is a slight mismatch between declaration and usage of $matches in "Use explanatory variables"

```
preg_match($cityZipCodeRegex, $address, $matches);
saveCityZipCode($matchers['city'], $matchers['zipCode']);
```
```
preg_match($cityZipCodeRegex, $address, $matches);
list(, $city, $zipCode) = $matchers;
```

**Comment by TomasVotruba** [comment]
Hey, could you send PR with the fix?

**Comment by thedebian** [comment]
Hi, done ! https://github.com/jupeter/clean-code-php/pull/30

**Comment by thedebian** [comment]
The issue has been resolved in commit https://github.com/jupeter/clean-code-php/commit/1ddff50a9b3bbf01ae02658499d9c2615265c22d
