### ISSUE TITLE
Getters and setters leads to anemic domain model anti-pattern

### ISSUE THREAD

**Issue by JMLamodiere** [jupeter/clean-code-php#31]
Hello and thanks for your work, I'll share it !

There is an issue wih [use getters and setters](https://github.com/jupeter/clean-code-php#use-getters-and-setters) , mostly the "setter part". With entities, it leads to the [anemic domain model anti-pattern](https://martinfowler.com/bliki/AnemicDomainModel.html). I think [this article with php example](https://beberlei.de/2012/08/22/building_an_object_model__no_setters_allowed.html)  from @beberlei explains it far better than I would.

The good news is that the example already seems correct : instead of having setters giving access to everything, there are mutators with explicit names : `withdrawBalance` and `depositBalance`, which already hold the logic to avoid negative balance. With simple getters/setters, this logic would be deported to another service, and nothing would prevent anyone from setting a negative balance anyway.

So, maybe we should only rename the title `use getters and setters` ?

**EDIT** : I did not suggest a new title. Maybe `Use object encapsulation` ? `Change entities* state through explicit mutators` ?

*(\* I say `entities` (or `model`) instead of `object` because some of them such as [value objects](https://en.wikipedia.org/wiki/Value_object) should be immutable. Their public methods should only return a new instance with the new values instead of changing their state.)*

**Comment by TomasVotruba** [comment]
Heys @JMLamodiere , let's move with this.

Could you send PR to with your title change suggestion? It would be easier to finish then

**Comment by JMLamodiere** [comment]
@TomasVotruba Seems like @peter-gribanov was faster than me :laughing: 

I'm totally fine with his PR #105

**Comment by TomasVotruba** [comment]
Thanks for you cooperation :+1: 

I've merged #105 so this can be closed.
