### ISSUE TITLE
Functions should do one thing

### ISSUE THREAD

**Issue by peter-gribanov** [jupeter/clean-code-php#38]
See [Functions should do one thing](https://github.com/jupeter/clean-code-php#functions-should-do-one-thing).

Example is terrible.
My proposal for improvement was rejected #22
Need to think about how to make an example easier and better.

**Comment by peter-gribanov** [comment]
Perhaps we should delete this section, because it's analogous of [Single Responsibility Principle (SRP)](https://github.com/jupeter/clean-code-php#single-responsibility-principle-srp).

**Comment by TomasVotruba** [comment]
> Perhaps we should delete this section, because it's analogous of Single Responsibility Principle (SRP).

Agreed. The logic is basically identical + OOP promotes more robuts behavior

Could you send PR to delete https://github.com/jupeter/clean-code-php#functions-should-do-one-thing ?

**Comment by peter-gribanov** [comment]
@TomasVotruba i create PR for this #170

**Comment by iainfogg** [comment]
Bob Martin's "Clean Architecture" book says that "a function should do one, and only one, thing" is different to SRP, I don't know if that sways your thinking about keeping this section? I'm new here, but I'd personally think it's good to keep, maybe with a better example as Peter suggested.

> Of all the SOLID principles, the Single Responsibility Principle (SRP) might be the least well understood. That’s likely because it has a particularly inappropriate name. It is too easy for programmers to hear the name and then assume that it means that every module should do just one thing. Make no mistake, there is a principle like that. A function should do one, and only one, thing. We use that principle when we are refactoring large functions into smaller functions; we use it at the lowest levels. But it is not one of the SOLID principles—it is not the SRP.

**Comment by TomasVotruba** [comment]
The logic is same for class/method/property, so it only needs to be said once.

See Occams razor.
