### ISSUE TITLE
Liskov Substitution Principle and type-checking

### ISSUE THREAD

**Issue by rey0bs** [jupeter/clean-code-php#46]
Hi,
There is a type-checking in Liskov Substitution Principle good example.
But type-checking is declared before like a bad practice.

PS : Thanks for this very good resource :)

**Comment by peter-gribanov** [comment]
This is a duplicate of #37

**Comment by TomasVotruba** [comment]
Hi @Saimount, we're glad you find it useful :)

I'm closing this in favor of mentioned existing issue.
Could you send PR with fix for that?
