### ISSUE TITLE
Translate into other languages

### ISSUE THREAD

**Issue by peter-gribanov** [jupeter/clean-code-php#59]
It would be great to make a section: **See in other languages**

Like in [clean-code-javascript](https://github.com/ryanmcdermott/clean-code-javascript#translation).

Already have some translations:
* [yangweijie/clean-code-php](https://github.com/yangweijie/clean-code-php) of @yangweijie
* [php-cpm/clean-code-php](https://github.com/php-cpm/clean-code-php) of @php-cpm

**Comment by TomasVotruba** [comment]
Good idea.

We could locate that in the end of the file. Could you send PR?

**Comment by php-cpm** [comment]
#64

**Comment by yangweijie** [comment]
#64 done job

**Comment by TomasVotruba** [comment]
Resolved by #64

**Comment by peter-gribanov** [comment]
I found another translation:

* https://github.com/fabioars/clean-code-php of @fabioars

**Comment by fabioars** [comment]
It's a work in progress, @peter-gribanov

**Comment by peter-gribanov** [comment]
@fabioars Great job. We will wait when you finish :wink:

**Comment by peter-gribanov** [comment]
I found another translations:
* https://github.com/jeanjar/clean-code-php/tree/pt-br of @jeanjar
* https://github.com/gbcr/clean-code-php of @gbcr
* https://github.com/panuwizzle/clean-code-php of @panuwizzle

**Comment by TomasVotruba** [comment]
Why not add them?

**Comment by jeanjar** [comment]
@peter-gribanov 

Hello guys, I'm still in progress

**Comment by peter-gribanov** [comment]
@TomasVotruba I add more translations #114

**Comment by peter-gribanov** [comment]
@fabioars @jeanjar @panuwizzle @gbcr
I add link to your repositories.
Don't hurry. Translate the text as you can.
Thank you for what you are doing.

**Comment by php-cpm** [comment]
https://github.com/gbcr/clean-code-php of @gbcr  pulls requests to me.
we'll do efforts on the Chinese Translation together in my repo https://github.com/php-cpm/clean-code-php , plz consider my repo the first one be to reached as @yangweijie 's translation is out of date.

**Comment by fikoborquez** [comment]
I translated it to spanish [here](https://github.com/fikoborquez/clean-code-php).

**Comment by peter-gribanov** [comment]
@fikoborquez I create PR for add your translation #115
Thanks for work.

**Comment by peter-gribanov** [comment]
Another novice translator:
 * https://github.com/XoDNr/clean-code-php of @XoDNr

**Comment by peter-gribanov** [comment]
Another novice translator:
* https://github.com/realodix/clean-code-php of @realodix
