### ISSUE TITLE
"Avoid Side Effects" contains invalid example.

### ISSUE THREAD

**Issue by RDIFB0** [jupeter/clean-code-php#8]
Global variable in PHP must be manually imported into local scope. [Example](https://3v4l.org/pmVQM) won't work.

**Comment by TomasVotruba** [comment]
Thanks for the report. How would you fix that?

**Comment by alexisLefebvre** [comment]
It looks like it has been fixed in #47.

**Comment by TomasVotruba** [comment]
@alexislefebvre You are right, thanks for update!

Closing as fixed
