### ISSUE TITLE
Why do not you use PHP >=7.1 right away in examples?

### ISSUE THREAD

**Issue by takeit** [jupeter/clean-code-php#85]
I understand that many developers are still using PHP 5 but it would be nice to have all the examples written in PHP 7.1 (to use, among other things, strict types), especially taking into an account that PHP 5.6 has no active support anymore, just the security updates.

**Comment by peter-gribanov** [comment]
Using PHP 7 affects examples [1](https://github.com/jupeter/clean-code-php#use-default-arguments-instead-of-short-circuiting-or-conditionals) and [2](https://github.com/jupeter/clean-code-php#avoid-type-checking-part-2).
In the examples where we are not tied to a particular version of PHP, it's better to use PHP 7, of course.
But i would not hurry with the transition to PHP 7 and postpone it at least until the end of the year.

**Comment by peter-gribanov** [comment]
I added PHP 7.1 type hinting in #110
@takeit Do you have any other wishes?
