### ISSUE TITLE
Good practices are not following PSR Naming Convention

### ISSUE THREAD

**Issue by helysousa** [jupeter/clean-code-php#95]
Good practice samples should follow PSR naming convention [http://www.php-fig.org/bylaws/psr-naming-conventions/], e.g. on Dependency Inversion Principle (DIP) good example, instead of 

```
interface Employee
{
    public function work();
}

class Human implements Employee
{
    public function work()
    {
        // ....working
    }
}

class Robot implements Employee
{
    public function work()
    {
        //.... working much more
    }
}

class Manager
{
    private $employee;

    public function __construct(Employee $employee)
    {
        $this->employee = $employee;
    }

    public function manage()
    {
        $this->employee->work();
    }
}
```
it should be

```
interface EmployeeInterface
{
    public function work();
}

class Human implements EmployeeInterface
{
    public function work()
    {
        // ....working
    }
}

class Robot implements EmployeeInterface
{
    public function work()
    {
        //.... working much more
    }
}

class Manager
{
    private $employee;

    public function __construct(EmployeeInterface $employee)
    {
        $this->employee = $employee;
    }

    public function manage()
    {
        $this->employee->work();
    }
}
```

**Comment by peter-gribanov** [comment]
This is a DDD naming style.

**Comment by peter-gribanov** [comment]
To better understand the benefits of this approach, look at the example of [Dependency Inversion Principle](https://github.com/jupeter/clean-code-php#dependency-inversion-principle-dip).
Refactoring did not affect to the `Manager` class.

**Comment by peter-gribanov** [comment]
In addition, this convention applies only to PSR packages. This convention does not belong to [PSR](http://www.php-fig.org/psr/).

**Comment by helysousa** [comment]
Peter, I understand that this convention does not belong to PSR, but clean code is not applicable itself the same way PSR isn't. I believe best practices could be applied in different contexts, even combined. With regards to following DDD naming style, I agree with your point.

Thank you for your time exposing your ideas, I appreciated it.
