### ISSUE TITLE
Preferred variable name for abbreviations? 

### ISSUE THREAD

**Issue by jimmerioles** [jupeter/clean-code-php#98]
How would you name a variable that are abbreviations? i.e. cache's time-to-live
``` php
$cacheTTL 

$cacheTtl

$TTL

$ttl
```

or  use unabbreviated?

`$timeToLive`

**Comment by peter-gribanov** [comment]
In PSR, there are no clear rules about this.
You can name variables as you see fit.
I would use name `$ttl`.

**Comment by jimmerioles** [comment]
Short simple and crips :+1: 

though `$timeToLive` kinda avoids mental mapping
